name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version to release
        required: true
  push
    # tags:        
    # - "*.*.*"



jobs:
  build_binaries:
    strategy:
        matrix:
          include:
            - os: ubuntu-18.04
              extension: so
              target: x86_64-unknown-linux-gnu
              code-target: linux-x64
            - os: ubuntu-18.04
              extension: so
              target: aarch64-unknown-linux-gnu
              code-target: linux-arm64
            - os: macos-11
              extension: dylib
              target: x86_64-apple-darwin
              code-target: darwin-x64
            - os: macos-11
              extension: dylib
              target: aarch64-apple-darwin
              code-target: darwin-arm64    
    runs-on: ${{matrix.os}}
    steps:  
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        target: ${{matrix.target}}
    - name: build mirrord-layer and cli
      run: cargo +nightly build --release -p mirrord -p mirrord-layer --target=${{matrix.target}}
    - name: build mirrord-cli
      run: cargo +nightly build --release --manifest-path=mirrord-layer/Cargo.toml --target=${{matrix.target}}
    - uses: actions/upload-artifact@v3
      with:
        name: $${matrix.target}
        path: |
          target/mirrord/release/mirrord
          target/mirrord/release/mirrord-layer.${{matrix.extension}}

  # # add publish docker image
  # release_vscode_ext:
  #   needs: build_binaries
  #   runs-on: ubuntu-latest
  #   steps:
  #   # This downloads all artifacts of the build
  #   - uses: actions/download-artifact@v3
  #     with:
  #       path: artifacts
  #   - run: npm install -g vsce typescript esbuild
  #   - run: mv target/release/libmirrord_layer.${{matrix.extension}} vscode-ext/
  #   - run: cd vscode-ext && npm install && tsc && vsce publish  {{github.event.inputs.version}} --allow-star-activation --target ${{matrix.code-target}} --pre-release
  #     env:
  #       VSCE_PAT: ${{ secrets.VSCE_PAT }}
